# Generated by Django 5.2 on 2025-04-08 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('types', models.CharField(choices=[('ML', 'MASALA'), ('PL', 'PLAIN'), ('OL', 'OOLONG'), ('EL', 'ELICHI'), ('GR', 'GINGER'), ('KL', 'KIWI')], max_length=2)),
            ],
        ),
    ]
